view/frontend/web/js/view/payment/method-renderer/bold-fastlane-method.js

- Removed `amount` from payment payload to let Checkout set it to the order total Checkout has calculated which might be different from the total Magento calculate

[INTER-4326] Remove amount for payments payload

---

view/frontend/web/js/view/payment/fastlane-methods.js

* Fixed console log that would happen when payment booster was installed but not enabled

[INTER-4401] Fixed property access on undefined when payment booster is disabled

---

view/frontend/web/js/view/payment/method-renderer/bold-fastlane-method.js

Magento_Checkout/js/action/set-billing-address updates cart billing address on backend and stops the loader as soon as request is completed. We do not need this extra request, as place order will send new billing address to backend.

(Payment Booster/Fastlane) Placing order for FL member in PPCP store does not show loading indicator while processing order.

---

Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Get.php
Service/ExpressPay/Order/Update.php
Service/ExpressPay/QuoteConverter.php
Test/Integration/Service/ExpressPay/Order/CreateTest.php
Test/Integration/Service/ExpressPay/Order/GetTest.php
Test/Integration/Service/ExpressPay/Order/UpdateTest.php
Test/Integration/Service/ExpressPay/QuoteConverterTest.php
Test/Integration/_files/quote_with_shipping_tax_and_discount.php
composer.json
etc/di.xml
etc/module.xml
etc/webapi.xml

Resolves [INTER-4629](https://boldapps.atlassian.net/browse/INTER-4629)
Resolves [INTER-4630](https://boldapps.atlassian.net/browse/INTER-4630)
Adds new Magento Web API endpoints for creating, updating and retrieving Express Pay (mobile wallet) orders.
| URI | Method | Parameters |Returns|
|--------|--------|--------|--------|
|/V1/express_pay/order/create | POST |`quote_mask_id`,`gateway_id`|`paypal_order_id`|
|/V1/express_pay/order/mine/create | POST |`quote_id`,`gateway_id`|`paypal_order_id`|
|/V1/express_pay/order/update | POST |`quote_mask_id`,`paypal_order_id`|VOID|
|/V1/express_pay/order/mine/update | POST |`quote_id`,`paypal_order_id`|VOID|
|/V1/express_pay/order/get | POST |`paypal_order_id`,`gateway_id`|See [spec]|
|/V1/express_pay/order/mine/get | POST …

[INTER-4629] [INTER-4630] Create Express Pay API Endpoints

---

Service/ExpressPay/Order/Update.php
Service/ExpressPay/QuoteConverter.php
view/frontend/web/js/model/express-pay.js
view/frontend/web/js/view/express-pay.js

- Frontend logic to implement the PPCP express pay callback for `onShippingAddressChange`.
- Updates the `Update` service to reflect changes to the checkout endpoint where Gateway Id and local are now required
- Fixes non-sequential array issue in QuoteConverter which was causing 'shipping_options' to be json encoded as an object instead of an array

Express Pay Shipping Address Change Callback

---

view/frontend/web/js/action/show-fastlane-shipping-address-form.js
view/frontend/web/js/model/fastlane.js
view/frontend/web/js/model/spi.js
view/frontend/web/js/view/form/element/email/fastlane-mixin.js
view/frontend/web/js/view/payment/method-renderer/bold-fastlane.js
view/frontend/web/js/view/shipping-address/list.js

Workaround to make Fastlane Instance loaded before Payments SDK starts rendering it's components. Should be properly fixed on payments SDK side.

Fix PPCP Fastlane is destroying SDK components in case Fastlane is loaded after.

---

view/frontend/web/js/action/convert-magento-address.js
view/frontend/web/js/model/spi.js

Adds the `onRequireOrderData` callback. This resolves the issue of the missing PayPal messaging when it was enabled in the Bold Checkout admin.

[CHK-5787] Add onRequireOrderData callback

---

composer.json
view/frontend/web/js/view/payment/method-renderer/bold-spi.js

On the payment step of checkout render wallet pay buttons using `renderPayments` instead of `renderWalletPayments`. This ensures the shipping strategy is set to `fixed`.

[CHK-5961] - Use renderPayments on payment step

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

The placeOrder logic for the SPI frame got broken during development of the express-pay feature. 
Reverting the previous code for this function to fix it.

Fix broken SPI placeOrder logic

---

view/frontend/web/js/model/spi.js

Adds the `onErrorPaymentOrder` callback. This will show a generic error message on the checkout page and console.error the parameter (if any) that is passed to the callback

Add onErrorPaymentOrder callback

---

Model/Payment/Gateway/Service.php

Setting the source parameter to platform tells checkout that the request is coming from the platform and it is not necessary to call back to the platform to update it. This avoids a deadlock due to locked database tables.

CHK-5926: Add source parameter to Checkout capture and refund calls

---

view/frontend/web/css/source/_module.less

Resolves [CHK-6278](https://boldapps.atlassian.net/browse/CHK-6278)
Magento has a core dependency on a PayPal Braintree module which is interfering with the styling of the PayPal buttons coming from the SDK. 
Given that we cannot remove the styles from this external module this PR fixes the styles within our module. 
[CHK-6278]: https://boldapps.atlassian.net/browse/CHK-6278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Braintree button styling

---

view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js

Bold Booster orders were selecting first listed shipping method, even when one is already selected. Now it is possible to complete an order with a different shipping method than the first listed.

[CHK-6365] Use Quote Shipping Method Before Defaulting to First Available

---

Model/Http/Client/RequestsLogger.php

Log Request was causing error on Magento version 2.4.3 when running `setup:upgrade` for not matching the declaration. 
Removing the return type so the declarations match.

[CHK-5203] Remove Void Return Type from Log Request

---

view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js

Update the `updateQuoteShippingMethodAction` to handle PPCP Gpay Express pay checkout
Return the first from the filtered available shipping rates because only one should match. Previously we checked the length and returned the first index. With the first function we will either return the matching shipping method or `undefined`
Removed the null check on `newMethod` for setting a default shipping method. Made use of the null coalescing to cover for `newMethod` to be `null` or `undefined` and put it directly in the set shipping param.

[CHK-4370] Enable GPAY PPCP Express Checkout

---

view/frontend/web/css/source/_module.less

- The font style for Wallet pays was override by font in M2 module, added custom css to make sure the font style consistent

EPS-170: Fix inconsistent font style

---

view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Add payment options to render google pay button with the SPI iframe.
- Renamed the fastlane payment options to avoid confusion with the non fastlane payment options
- Added backup order id path from the payment data because google do be like that sometimes
Resolves [CHK-6462](https://boldapps.atlassian.net/browse/CHK-6462)
[CHK-6462]: https://boldapps.atlassian.net/browse/CHK-6462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-6462] Enable Google Pay Button on Payment Step

---

view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
view/frontend/web/js/model/fastlane.js

On older M2 versions, like 2.4.5, if you define prototype the billing address details can spit out javascript as text.
Removed the import from `fastlane.js` and changed the update shipping method callback function to use `[0]` instead of `.first()` when filtering for the currently selected shipping method.
Replaced the `prototype.wrap()` called on `appendChild` with overriding require load to add credentials for the fast lane script
Fixes [CHK-6869](https://boldapps.atlassian.net/browse/CHK-6869)
[CHK-6869]: https://boldapps.atlassian.net/browse/CHK-6869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-6869] Remove Prototype Import to Prevent JS Dump

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

- Add shop name as option when rendering apple pay button above SPI, the same option has passed in the apple pay express button

EPS-668: Add shop name as option when rendering apple payment button

---

composer.json

* EPS-668: Use class name instead of ID for Express Pay buttons by @zliu7878 in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/145
* CHK-6924: Don't remove www. prefix from configuration group label by @benzeghers-bold in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/148
* CHK-6869 Remove Prototype Import to Prevent JS Dump by @TimeBones in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/146
* EPS-668: Add shop name as option when rendering Apple Pay payment button by @zliu7878 in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/149
Resolves [CHK-6986](https://boldapps.atlassian.net/browse/CHK-6986)
[CHK-6986]: …

CHK-6986 release version 2.2.8

---

view/frontend/web/js/action/express-pay/update-quote-address-action.js
view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js

The email address and phone number are not provided in the `onUpdatePaymentOrder` callback for wallet pays. This change updates the addresses in the `onApprovePaymentOrder` to include this data.
Fixes [CHK-6262](https://boldapps.atlassian.net/browse/CHK-6262)
[CHK-6262]: https://boldapps.atlassian.net/browse/CHK-6262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6262: Update address on approve payment for wallet pays

---

Service/ExpressPay/QuoteConverter.php

Fixes a bug where a shipping rate was not imported successfully, but still sent to PayPal as part of the order creation request. This caused an issue since PayPal validates that shipping options must have a label.
Added a bit of code to ignore failed rate imports in the PayPal request.

CHK-7004 - filter out shipping options in PayPal request that Magento could not import

---

Model/Order/HydrateOrderFromQuote.php

In Magento it is possible to save Tax Zones with numeric `tax identifiers`. We use this field as the rate/display name in the simple order. 
When saving an integral value in the tax identifier, the Sidekick hydrate order request fails due to this value being an integer, with the Sidekick API expecting a string.

CHK-6516 - support for non-string tax identifiers in Magento tax zones

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Adding the ability to show the Google Pay button in the wallet pays payment section when fastlane is enabled.
Resolves [CHK-7028](https://boldapps.atlassian.net/browse/CHK-7028)
[CHK-7028]: https://boldapps.atlassian.net/browse/CHK-7028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7028] Add google pay button to wallet pay options when fastlane enabled

---

Api/Quote/GetQuoteInterface.php
Model/InitOrderFromQuote.php
Observer/Product/ExpressPayBeforeAddToCartObserver.php
Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Update.php
Service/Quote/GetQuote.php
UI/PaymentBoosterConfigProvider.php
ViewModel/ExpressPay.php
etc/di.xml
etc/frontend/events.xml
etc/webapi.xml
view/frontend/layout/catalog_product_view.xml
view/frontend/layout/catalog_product_view_type_bundle.xml
view/frontend/templates/express-pay.phtml
view/frontend/web/js/action/express-pay/create-wallet-pay-order-action.js
view/frontend/web/js/action/express-pay/get-active-quote-id-action.js
view/frontend/web/js/express-pay-storefront.js
view/frontend/web/js/model/spi.js
view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js

Adding Express Pay modal to the PDP
Adding before cart add event to clear cart for quick purchase 
Adding support for SDK onClick event to add item to cart on pdp 
Adding page source argument to express pay xml to facilitate above add
NOTE: requires fixes in parent branch to implement cache bust causing observer not to fire.

[CHK-4614] Adobe Commerce: As a brand using Payment Booster, I want to offer branded PPCP buttons on my product pages

---

Api/Quote/GetQuoteInterface.php
Model/Config.php
Service/Quote/GetQuote.php
etc/webapi.xml
view/frontend/web/js/action/express-pay/add-product-to-cart-action.js
view/frontend/web/js/action/express-pay/get-active-quote-action.js
view/frontend/web/js/action/express-pay/get-required-order-data-action.js
view/frontend/web/js/model/spi.js
view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js

Removing Awaits in onclick functionality to allow apple pay to render immediately.
Adding default data in onrequire for apply pay orders so the data is instead populated in the onupdate event to facilitate this.
Note that future state for this fix will include more accurate dummy data and guards around possible race conditions. That fix will be included in [CHK-7179]
Fixes [CHK-7145](https://boldapps.atlassian.net/browse/CHK-7145)
[CHK-7179]: https://boldapps.atlassian.net/browse/CHK-7179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-7145]: https://boldapps.atlassian.net/browse/CHK-7145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7145] Fix Quote Initialization for Apple Pay on Product Detail Page

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Add an error for SPI tokenize event that is unsuccessful and there is no payment ID. Additionally if the tokenize does not have a payment id the case will flow into the SPI tokenize failed so clear loading states and the payment id observable. This is because SPI can return the tokenized even with `success: false` in addition to the tokenized failed as separate events.
Fixes [CHK-4774](https://boldapps.atlassian.net/browse/CHK-4774)
[CHK-4774]: https://boldapps.atlassian.net/browse/CHK-4774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-4774 Add error message for invalid CC details in SPI

---

composer.json

* CHK-4774 Add error message for invalid CC details in SPI by @TimeBones in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/161

Release version 2.2.11

---

view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
view/frontend/web/js/model/spi/callbacks/on-create-payment-order-callback.js

For non-express pay orders, the customer would enter their address but then it would be replaced with the address from PayPal. This change keeps the address the customer entered in Magento.
Related EPS change: https://github.com/bold-commerce/enhanced-payment-service/pull/500
Fixes [CHK-6966](https://boldapps.atlassian.net/browse/CHK-6966)
[CHK-6966]: https://boldapps.atlassian.net/browse/CHK-6966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6966: Don't update address when not express pay

---

view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js

- Fixed an issue where non-express wallet-pay shipping data collected by Magento was being replaced with Paypal order data which may not be accurate to the quote.
Fixes [CHK-7483](https://boldapps.atlassian.net/browse/CHK-7483)
[CHK-7483]: https://boldapps.atlassian.net/browse/CHK-7483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7483: Non Express wallet pay shipping data

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Resolves: [CHK-7528](https://boldapps.atlassian.net/browse/CHK-7528)
Set the paymentId to null on `placeOrderClick` ensuring that a new tokenize call is made on each place order attempt. 
This resolves the issue where after an initial transaction decline, subsequent valid payments would not succeed.
[CHK-7528]: https://boldapps.atlassian.net/browse/CHK-7528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7528] Reset paymentId on placeOrderClick

---

view/frontend/web/js/model/spi.js

(Magento 2/Bold Booster v2) Stripe Credit card frame is not loaded in Payment section with payment_sdk error in Console
Fixes [CHK-7553](https://boldapps.atlassian.net/browse/CHK-7553)
[CHK-7553]: https://boldapps.atlassian.net/browse/CHK-7553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7553: Fix Error Preventing Stripe Credit Card Form From Loading

---

etc/adminhtml/system.xml

Fixes [CHK-7565](https://boldapps.atlassian.net/browse/CHK-7565)
[CHK-7565]: https://boldapps.atlassian.net/browse/CHK-7565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7565: Hide Enable Digital Wallets on Cart Page setting when Payment Booster is disabled

---

view/frontend/web/js/action/express-pay/update-quote-address-action.js
view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js

Resolves: [CHK-7418](https://boldapps.atlassian.net/browse/CHK-7418)
Fix issue where no phone number was being saved on the shipping or billing address of an order. 
Add missing check for gathering the phone number in the update address action. Also updated our address converter to fallback to the billing address phone number if no number is explicitly provided with the shipping address. 
[CHK-7418]: https://boldapps.atlassian.net/browse/CHK-7418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7418] - Fix missing phone number on addresses

---

view/frontend/web/js/action/express-pay/update-quote-braintree-action.js
view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js

Currently, for the wallet payment buttons at the payment step, we use both the shipping and billing addresses from Magento. With this change, the shipping address will continue from Magento, while the billing address will now be retrieved from the respective PayPal/Google/Apple Pay model.
Fixes [CHK-7563](https://boldapps.atlassian.net/browse/CHK-7563)
[CHK-7563]: https://boldapps.atlassian.net/browse/CHK-7563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7563: Fix wrong billing address for wallet pay buttons at payment step

---

Model/CheckoutData.php
etc/adminhtml/system.xml

Fixes [CHK-7711](https://boldapps.atlassian.net/browse/CHK-7711)
[CHK-7711]: https://boldapps.atlassian.net/browse/CHK-7711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7711: Hide configuration on default scope and add throw error if shop_id is not configured in init

---

Plugin/ReCaptcha/DisableRecaptchaForExpressPayPlugin.php
Service/ExpressPay/Callback/OnApprove.php
etc/di.xml
etc/webapi.xml
view/frontend/web/js/action/express-pay/on-approve-express-pay-order-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js

Using Express Pay, with ReCaptcha enabled, the PayPal modal will complete prior to ReCaptcha executing on place order event. So we are observing an authorization in the customer's PPCP account for each time ReCaptcha failed.
We'll work around the problem for now by overriding the ReCaptcha when paying with the PayPal express pay modal. This solution was signed off by Product.
The PayPal `onApprove` callback is the very last action taken by this modal after payment is authorized. Ended up using the `DataPersistor` to store a flag. Seemed appropriate but I'm still new to Magento.

CHK-7315 - fix Express Pay multiple authorizations when ReCaptcha fails

---

etc/csp_whitelist.xml

While testing Front end logging with Bold Booster extension we noticed that the EPS styles were not allowed for local development environments.
This add it to the allow list enabling local environments without the need to hardcode in CSP.
Relates to [CHK-7256](https://boldapps.atlassian.net/browse/CHK-7256)
[CHK-7256]: https://boldapps.atlassian.net/browse/CHK-7256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7256: Add Bold local env domain to style-src CSP whitelist

---

Plugin/ReCaptcha/Model/DisableRecaptchaForExpressPayPlugin.php

Fix an issue with the namespace and file location for the DisableRecaptchaForExpressPayPlugin.
Moved the file to a `Model` subdirectory since it is a plugin for a Recaptcha Model file. Please let me know if there are different standards that should be followed.

CHK-7818 - fix namespace for DisableRecaptchaForExpressPayPlugin.php

---

PATCHES.md
etc/csp_whitelist.xml
patches/MAGETWO-PAYMENT-BOOSTER_2.3.x.patch

There are incompatible content security policies used in Adobe Commerce 2.3.x and Adobe Commerce 2.4.x, so we cannot have a single CSP whitelist for both versions.
1. Updated `csp_whitelist.xml` to be valid for 2.4.x
2. Added patch to make `csp_whitelist.xml` compatible with 2.3.x
Fixes [CHK-7629](https://boldapps.atlassian.net/browse/CHK-7629)
[CHK-7629]: https://boldapps.atlassian.net/browse/CHK-7629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7629: Update CSP Whitelist for 2.4.x Versions and Add Compatibility Patch for 2.3.x Versions

---

Service/ExpressPay/QuoteConverter.php

- Ensure item total is always equal to unit amount * qty.
When a merchant has `Catalog Prices` set to `Including Tax` - a quote items rowTotal is not always equal to an items unit price * qty.  Here is an example quote from Magento that demonstrates this:
```
"items": [
{
"name": "Fusion Backpack",
"sku": "24-MB02",
"unit_amount": {
"currency_code": "USD",
"value": "106.56"
},
"quantity": 2,
"is_shipping_required": true
}
],
"item_total": {
"currency_code": "USD",
"value": "213.11"
},
"amount": {
"currency_code": "USD",
"value": "213.00"
},
"tax_total": {
"currency_code": "USD",
"value": "37.51"
},
"discount": {
"currency_code": "USD",
"value": "52.00"
}
},
"shipping_strategy": "dynamic"
}
```
Note, that the item price is 106.56. The items cost set in the merchants admin is 130, with a …

CHK-7921: Resolve rounding issues

---

Observer/Product/ExpressPayAfterAddToCartObserver.php
etc/frontend/events.xml

Adding after add dispatch event to supress add to cart message appearing on checkout/add
Fixes [CHK-7161](https://boldapps.atlassian.net/browse/CHK-7161)
[CHK-7161]: https://boldapps.atlassian.net/browse/CHK-7161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7161] Adobe Commerce: Remove "Added to cart" alert on checkout success page

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

- Remove 'pay with section' from error message as the sections use icons now
- Moved error message to constant for reusability 
- Refactored switch statement for redundancy 
- when `tokenized` is called and the iframe isn't present, we stop the loader and show an error message instead of just failing silently and having the loader persist indefinitely

CHK-7525 Show error and stop loader when tokenizing without iframe present

---

Service/ExpressPay/Order/Create.php
Test/Integration/Service/ExpressPay/Order/CreateTest.php
view/frontend/web/js/action/express-pay/create-wallet-pay-order-action.js

Adds the `public_order_id` to the PayPal create order request, to allow for easy association between `paypalDebugId` and orders. See the specification here
https://github.com/bold-commerce/engineering-specs/pull/177/files
Resolves [CHK-7721](https://boldapps.atlassian.net/browse/CHK-7721)
[CHK-7721]: https://boldapps.atlassian.net/browse/CHK-7721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7721 - add public_order_id to PayPal create order request

---

Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
ViewModel/ExpressPay.php
view/frontend/templates/express-pay-minicart.phtml
view/frontend/templates/express-pay-product.phtml

Restores logic for setting customer data and authentication state in the browser's `window` object removed by commit f268c4a6.
Fixes [CHK-7953](https://boldapps.atlassian.net/browse/CHK-7953)
[CHK-7953]: https://boldapps.atlassian.net/browse/CHK-7953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7953: Fix Errors for Authenticated Customers When Paying via Digital Wallets

---

composer.json

- CHK-8046: Fix Incompatibility With Magento 2.3.x and  PHP 7.x Versions (#250)
Resolves [CHK-8045](https://boldapps.atlassian.net/browse/CHK-8045)
[CHK-8045]: https://boldapps.atlassian.net/browse/CHK-8045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8045: Release Version 2.4.4

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Aligns the rendering of the "Place Order" button in the SPI frame to work with multiple payment gateways.
Fixes [CHK-8035](https://boldapps.atlassian.net/browse/CHK-8035)
[CHK-8035]: https://boldapps.atlassian.net/browse/CHK-8035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8035 - render Place Order button for credit card gateways

---

.github/CODEOWNERS

We want to update our codeowners to use a GitHub team to expand who can be in charge of reviewing code.
Relates to [CHK-8014](https://boldapps.atlassian.net/browse/CHK-8104)

CHK-8104: Update CODEOWNERS

---

view/frontend/web/js/model/fastlane.js

Setting `window.braintree.version` to force PPCP Fastlane to load the specified version.

CHK-8322: Add version tolerance to ppcp fastlane

---

composer.json

* CHK-8322: Add version tolerance to ppcp fastlane by @kfalkowski11 in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/283
**Full Changelog**: https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/compare/v2.5.4...v2.5.5

CHK-8350: Increment version to 2.5.5

---

patches/SINGLE-STORE-MODE-BOOSTER_2.3.x.patch

Patch for Magento 2.3.x single-store-mode.
This change ensures the config field is rendered when the admin is operating in default scope, which is the only available scope in Single-Store Mode.

CHK-7977: Fix for single-store-mode

---

Api/Integration/ValidateApiInterface.php
Block/Adminhtml/System/Config/Form/Field/IntegrateCheckoutApiButton.php
Controller/Adminhtml/Integration/Integrate.php
Controller/Adminhtml/Log/Export.php
Model/Config.php
Model/GenerateSharedSecret.php
Model/Integration/IntegrateBoldCheckout.php
Model/Integration/ValidateApi.php
Observer/Checkout/ConfigureShopObserver.php
etc/adminhtml/system.xml
etc/di.xml
etc/webapi.xml

* Add Bold Checkout API integration enablement flag.
* Internally add Bold Checkout API integration validated flag.
* Add endpoint `/V1/shops/:shopId/integration/validate` to receive checkout validation call of the authorization.
* Enable
* Integrate manually
* Successful to configure integration
* Failed to configure Integration

CHK-9302: Bold Checkout API integration Key exchange

---

Console/Command/IntegrateCheckoutApi.php
etc/di.xml

Create a command for the CLI to integrate Checkout API with the key exchange.

CHK-9309: Integrate Checkout Api CLI
