Api/Data/Http/Client/ResultInterface.php
Api/Http/ClientInterface.php
Model/Http/BoldClient.php
Model/Http/Client/Command/DeleteCommand.php
Model/Http/Client/Command/GetCommand.php
Model/Http/Client/Command/PatchCommand.php
Model/Http/Client/Command/PostCommand.php
Model/Http/Client/Command/PutCommand.php
Model/Http/Client/Result.php
Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Get.php
Service/ExpressPay/Order/Update.php
Test/Integration/Service/ExpressPay/Order/CreateTest.php
Test/Integration/Service/ExpressPay/Order/GetTest.php
Test/Integration/Service/ExpressPay/Order/UpdateTest.php
etc/di.xml

Relates to [CHK-4407](https://boldapps.atlassian.net/browse/CHK-4407), [CHK-4408](https://boldapps.atlassian.net/browse/CHK-4408)
[CHK-4407]: https://boldapps.atlassian.net/browse/CHK-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-4408]: https://boldapps.atlassian.net/browse/CHK-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-4407, CHK4408: Remove Dependency on Base Checkout Extension

---

Model/Config.php
UI/Payment/PaymentBoosterConfigProvider.php
etc/adminhtml/system.xml
etc/config.xml
etc/csp_whitelist.xml
view/frontend/layout/checkout_index_index.xml
view/frontend/web/css/source/_module.less
view/frontend/web/js/model/express-pay.js
view/frontend/web/js/model/fastlane.js
view/frontend/web/js/view/express-pay.js
view/frontend/web/template/express-pay.html

Adds the PPCP express pay buttons to the top of the shipping step of checkout.

Add PPCP express buttons to checkout

---

view/frontend/requirejs-config.js
view/frontend/web/css/source/_module.less
view/frontend/web/js/model/step-navigator-mixin.js
view/frontend/web/js/view/payment/method-renderer/bold-method.js

Adding pigi sca actions to handle 3ds events.

[CHK-4928] Add pigi sca actions for 3ds

---

Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Get.php
Service/ExpressPay/Order/Update.php
Service/ExpressPay/QuoteConverter.php
Test/Integration/Service/ExpressPay/Order/CreateTest.php
Test/Integration/Service/ExpressPay/Order/GetTest.php
Test/Integration/Service/ExpressPay/Order/UpdateTest.php
Test/Integration/Service/ExpressPay/QuoteConverterTest.php

Fixes [CHK-4407](https://boldapps.atlassian.net/browse/CHK-4407), [CHK-4408](https://boldapps.atlassian.net/browse/CHK-4408)
[CHK-4407]: https://boldapps.atlassian.net/browse/CHK-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-4408]: https://boldapps.atlassian.net/browse/CHK-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-4407, CHK-4408: Fix Bugs in Express Pay API Endpoints

---

view/frontend/web/js/model/express-pay.js
view/frontend/web/js/view/express-pay.js

Frontend logic to implement the PPCP express pay callback for `createOrder`.

Express Pay Create Order Callback

---

Service/ExpressPay/QuoteConverter.php
Test/Integration/Service/ExpressPay/QuoteConverterTest.php
composer.json

Relates to [CHK-4407](https://boldapps.atlassian.net/browse/CHK-4407),  [CHK-4408](https://boldapps.atlassian.net/browse/CHK-4408)
[CHK-4407]: https://boldapps.atlassian.net/browse/CHK-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-4408]: https://boldapps.atlassian.net/browse/CHK-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-4407, CHK-4408]: Convert Custom Quote Totals to Express Pay Order Items

---

.github/CODEOWNERS

Resolves [CHK-5478](https://boldapps.atlassian.net/browse/CHK-5478)
[CHK-5478]: https://boldapps.atlassian.net/browse/CHK-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-5478: Define Default Code Reviewers for Repository

---

Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Get.php
Service/ExpressPay/Order/Update.php
Service/ExpressPay/QuoteConverter.php
Test/Integration/Service/ExpressPay/Order/GetTest.php
Test/Integration/Service/ExpressPay/Order/UpdateTest.php
UI/PaymentBoosterConfigProvider.php
etc/frontend/di.xml
view/frontend/web/js/model/express-pay.js
view/frontend/web/js/model/fastlane.js
view/frontend/web/js/view/express-pay.js

Resolves [CHK-4546](https://boldapps.atlassian.net/browse/CHK-4546)
[CHK-4546]: https://boldapps.atlassian.net/browse/CHK-4546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Express Pay Shipping Method Change Callback

---

view/frontend/web/template/express-pay.html

Removing or and container line from view

[CHK-5894] Drop "or" From Express Checkout for M2

---

composer.json

Remove external dev dependency

Remove external dev dependency

---

Service/ExpressPay/QuoteConverter.php

Partially reverts changes made by [CHK-6101](https://boldapps.atlassian.net/browse/CHK-6101). These changes need more testing.
[CHK-6101]: https://boldapps.atlassian.net/browse/CHK-6101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert changes made to quote conversion logic in PR #101

---

Service/ExpressPay/Order/Create.php
Service/ExpressPay/QuoteConverter.php

Fixes [CHK-6101](https://boldapps.atlassian.net/browse/CHK-6101)
[CHK-6101]: https://boldapps.atlassian.net/browse/CHK-6101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6101: Fix Incorrect Shipping Totals After Quote to Express Pay Order Conversion

---

composer.json

New release with fixes for shipping calculation issues.

Increment extension version number to 2.1.2

---

Service/ExpressPay/Order/Create.php
Service/ExpressPay/QuoteConverter.php
etc/csp_whitelist.xml
view/frontend/web/js/action/express-pay/get-required-order-data-action.js
view/frontend/web/js/action/express-pay/save-shipping-information-action.js
view/frontend/web/js/action/express-pay/update-quote-address-action.js
view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
view/frontend/web/js/model/spi/callbacks/on-create-payment-order-callback.js
view/frontend/web/js/model/spi/callbacks/on-update-payment-order-callback.js

Resolves [CHK-4371](https://boldapps.atlassian.net/browse/CHK-4371)
Resolves [CHK-6200](https://boldapps.atlassian.net/browse/CHK-6200)
Adds ApplePay compatibility for PPCP gateway. 
Also resolves error with creating a wallet pay order on the payment step of checkout.
[CHK-4371]: https://boldapps.atlassian.net/browse/CHK-4371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-6200]: https://boldapps.atlassian.net/browse/CHK-6200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ApplePay for PPCP

---

Service/ExpressPay/QuoteConverter.php

Resolves: [CHK-6261](https://boldapps.atlassian.net/browse/CHK-6261)
Fix for issue where email was not properly getting sent in the `create` call for authenticated customers
[CHK-6261]: https://boldapps.atlassian.net/browse/CHK-6261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix for auth customers and express pay

---

composer.json

Releasing ApplePay for PPCP and some bug fixes

Version Bump 2.2.0

---

composer.json

- Improve logging for configuration issues
- Fixed shipping rate total mismatch

Release v2.2.1

---

Service/ExpressPay/QuoteConverter.php

Fixes incorrect formatting of amounts leading to errors being thrown for values over 1,000.
Fixes [CHK-6312](https://boldapps.atlassian.net/browse/CHK-6312)
[CHK-6312]: https://boldapps.atlassian.net/browse/CHK-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6312: Fix errors thrown for prices greater than 1000

---

composer.json

- Release of 2.2.2 to include numeric updates

Release v2.2.2

---

Test/Integration/Service/ExpressPay/QuoteConverterTest.php

Updates test to account for changes made in commit 1c354a47.

CHK-4371: Add name and phone number to quote converter test data

---

composer.json

Resolves [CHK-6470](https://boldapps.atlassian.net/browse/CHK-6470)
[CHK-6470]: https://boldapps.atlassian.net/browse/CHK-6470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6470: Update composer version number to 2.2.3

---

.github/CODEOWNERS

Relates to [CHK-5478](https://boldapps.atlassian.net/browse/CHK-5478)
[CHK-5478]: https://boldapps.atlassian.net/browse/CHK-5478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-5478: Update CODEOWNERS

---

etc/csp_whitelist.xml

Resolves: https://boldapps.atlassian.net/browse/CHK-6743

Fix errors with csp_whitelist

---

composer.json

Version bump to release hotfix related to https://boldapps.atlassian.net/browse/CHK-6743

Bump composer to 2.2.5 for release

---

Model/CheckoutData.php
Model/Eps/GetFastlaneStyles.php
UI/PaymentBoosterConfigProvider.php
etc/adminhtml/system.xml

Resolves [CHK-6522](https://boldapps.atlassian.net/browse/CHK-6522)
[CHK-6522]: https://boldapps.atlassian.net/browse/CHK-6522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6522: If configuration group is empty default to the store domain

---

etc/adminhtml/system.xml

Fixes [CHK-6522](https://boldapps.atlassian.net/browse/CHK-6522)
[CHK-6522]: https://boldapps.atlassian.net/browse/CHK-6522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6522: Make Configuration Group Label setting optional

---

composer.json

Resolves [CHK-6795](https://boldapps.atlassian.net/browse/CHK-6795)
[CHK-6795]: https://boldapps.atlassian.net/browse/CHK-6795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6795: Update composer version number to 2.2.6

---

view/frontend/web/js/model/spi.js

Fixes [CHK-6773](https://boldapps.atlassian.net/browse/CHK-6773)
[CHK-6773]: https://boldapps.atlassian.net/browse/CHK-6773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6773: Validate Agreements Before Render

---

view/frontend/web/css/source/_module.less
view/frontend/web/js/view/bold-express-pay.js
view/frontend/web/template/express-pay.html

- Fix css issue when hover the goggle pay button
- Add loading section for wallet pays
Resolves [EPS-170](https://boldapps.atlassian.net/browse/EPS-170)
[EPS-170]: https://boldapps.atlassian.net/browse/EPS-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EPS-170: Add loading section for wallet pays

---

view/frontend/web/js/model/spi.js
view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-6821](https://boldapps.atlassian.net/browse/CHK-6821)
[CHK-6821]: https://boldapps.atlassian.net/browse/CHK-6821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6821: Fix Place Order Error When Agreements Are Not Accepted

---

view/frontend/web/css/source/_module.less

- Use class name as css selector instead of id

EPS-668: Use class name instead of id

---

Model/Eps/GetFastlaneStyles.php
UI/PaymentBoosterConfigProvider.php

Fixes [CHK-6294](https://boldapps.atlassian.net/browse/CHK-6294)
[CHK-6294]: https://boldapps.atlassian.net/browse/CHK-6294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6924: Don't remove www. prefix from configuration group label

---

view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js

Before:
After (Apple Pay order):
After (Google Pay order):
Fixes [CHK-6308](https://boldapps.atlassian.net/browse/CHK-6308)
[CHK-6308]: https://boldapps.atlassian.net/browse/CHK-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6308: Fix incomplete shipping address with Braintree Apple/Google Pay

---

composer.json

Increments version number for new release of Module.

increment version number to 2.2.9

---

Service/ExpressPay/QuoteConverter.php

Revert changes made by PR #156 in favor of changes made by PR #154 
This reverts commit bd3944c1006fb73706cd4510eff7eada89a22a4d, reversing changes made to 7523e8cd61fca43fdb8e6cebc484142e51ac4266.
Relates to [CHK-7004](https://boldapps.atlassian.net/browse/CHK-7004)
[CHK-7004]: https://boldapps.atlassian.net/browse/CHK-7004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7004: Revert PR #156

---

ViewModel/ExpressPay.php
view/frontend/templates/express-pay.phtml

Resolves: https://boldapps.atlassian.net/browse/CHK-6967
Adds required customer data to the window object to allow for authenticated customers to checkout using express pay buttons on the product page, cart, and mini-cart.

[CHK-6967] Add missing window data for auth customers

---

etc/adminhtml/system.xml

Resolves: https://boldapps.atlassian.net/browse/CHK-7008

[CHK-7008] Update admin express pay verbiage to 'Digital Wallets'

---

UI/PaymentBoosterConfigProvider.php
ViewModel/ExpressPay.php
view/frontend/templates/express-pay.phtml
view/frontend/web/js/express-pay-storefront.js
view/frontend/web/js/model/spi.js

Resolves https://boldapps.atlassian.net/browse/CHK-7163
Fixes bug where on the PDP the mini-cart was checking out with the product whose page we were on instead of the items already in the cart.

[CHK-7163] Fix mini-cart digital wallets purchasing wrong item on PDP

---

view/frontend/templates/express-pay.phtml

Resolves: https://boldapps.atlassian.net/browse/CHK-7198
Fixes issue with placing a PayPal order in the mini-cart for authenticated customers. 
Also fixes button rendering issue on product pages

[CHK-7198] Fix PayPal in Mini-cart for Auth users

---

composer.json

Resolves [CHK-7314](https://boldapps.atlassian.net/browse/CHK-7314)
[CHK-7314]: https://boldapps.atlassian.net/browse/CHK-7314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7314: Release version 2.2.12

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-6833](https://boldapps.atlassian.net/browse/CHK-6833)
[CHK-6833]: https://boldapps.atlassian.net/browse/CHK-6833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6833 fixing the Place Order button showing error

---

composer.json

Resolves [CHK-7466](https://boldapps.atlassian.net/browse/CHK-7466)
[CHK-7466]: https://boldapps.atlassian.net/browse/CHK-7466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7466: Release Version 2.2.13

---

view/frontend/web/js/model/spi.js
view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-6987](https://boldapps.atlassian.net/browse/CHK-6987)
[CHK-6987]: https://boldapps.atlassian.net/browse/CHK-6987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-6987 Fixing the Amasty GDPR module checkboxes validation

---

composer.json

Resolves [CHK-7467](https://boldapps.atlassian.net/browse/CHK-7467)
[CHK-7467]: https://boldapps.atlassian.net/browse/CHK-7467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7467 release 2.2.14

---

composer.json

Resolves: [CHK-7543](https://boldapps.atlassian.net/browse/CHK-7543)
[CHK-7543]: https://boldapps.atlassian.net/browse/CHK-7543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7543] Release Version 2.3.1

---

Api/Data/Order/Payment/PaymentInterface.php
Api/Data/Order/Payment/TransactionInterface.php
Api/Order/UpdatePaymentsInterface.php
Model/Order/Payment.php
Model/Order/Transaction.php
Model/Order/UpdatePayments.php
Model/Order/UpdatePayments/CreateInvoice.php
etc/di.xml

Resolves [CHK-7544](https://boldapps.atlassian.net/browse/CHK-7544)
[CHK-7544]: https://boldapps.atlassian.net/browse/CHK-7544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7544: Create capture when receiving capture result from checkout

---

composer.json

Resolves [CHK-7625](https://boldapps.atlassian.net/browse/CHK-7625)
[CHK-7625]: https://boldapps.atlassian.net/browse/CHK-7625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7625: Release Version v2.3.2

---

Model/Config.php
Model/Payment/Gateway/Service.php
Plugin/Quote/Model/QuoteManagement/DisableBoldAddressValidationPlugin.php
UI/Payment/WalletPaymentsConfigProvider.php
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml
etc/frontend/di.xml
etc/payment.xml
view/frontend/layout/checkout_index_index.xml
view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
view/frontend/web/js/view/payment/bold-payments.js
view/frontend/web/js/view/payment/method-renderer/bold-spi.js
view/frontend/web/js/view/payment/method-renderer/bold-wallet-payments.js
view/frontend/web/template/payment/wallet-payments.html

- Add a new payment option for wallet pay
- Allow the option in Magento admin to change wallet pay title
Relates to [EPS-169](https://boldapps.atlassian.net/browse/EPS-169)
[EPS-169]: https://boldapps.atlassian.net/browse/EPS-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EPS-169: Create New Wallet Payments Payment Method

---

composer.json

Resolves: [CHK-7647](https://boldapps.atlassian.net/browse/CHK-7647)
[CHK-7647]: https://boldapps.atlassian.net/browse/CHK-7647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7647] Release Version 2.4.0

---

composer.json

Resolves [CHK-7737](https://boldapps.atlassian.net/browse/CHK-7737)
[CHK-7737]: https://boldapps.atlassian.net/browse/CHK-7737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7737: Update version number to 2.4.1

---

view/frontend/web/js/action/express-pay/save-shipping-information-action.js

Fix the PayPal modal to display error message "Store does not ship to selected address" when customer's address is not one that the merchant ships to. Previously, this would cause the modal to infinitely load and not display any error message to the customer.
The `.fail` piece was returning an unfulfilled promise, that didn't play nice with the PayPal modal, changing to a rejected promise that allows the PayPal modal to display the error message.
Fixes [CHK-6948](https://boldapps.atlassian.net/browse/CHK-6948)
[CHK-6948]: https://boldapps.atlassian.net/browse/CHK-6948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-6948] Fix paypal modal when shop doesn't ship to selected address

---

composer.json

* [CHK-6948] Fix paypal modal when shop doesn't ship to selected address by @kfalkowski11 in https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/pull/206
**Full Changelog**: https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/compare/v2.4.1...v2.4.2
[CHK-6948]: https://boldapps.atlassian.net/browse/CHK-6948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Resolves [CHK-7770](https://boldapps.atlassian.net/browse/CHK-7770)
[CHK-7770]: https://boldapps.atlassian.net/browse/CHK-7770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7770] Increase version number to 2.4.2

---

Plugin/Framework/App/FrontControllerPlugin.php
view/frontend/web/js/action/express-pay/get-required-order-data-action.js
view/frontend/web/js/express-pay-storefront.js

Fixes [CHK-7780](https://boldapps.atlassian.net/browse/CHK-7780)
[CHK-7780]: https://boldapps.atlassian.net/browse/CHK-7780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7780: Fix Errors Thrown by Digital Wallets in Mini Cart on Product Detail Page

---

Plugin/Framework/App/ActionInterfacePlugin.php
Test/Integration/Plugin/Framework/App/ActionInterfacePluginTest.php
ViewModel/ExpressPay.php
etc/di.xml
etc/frontend/di.xml

Fixes [CHK-7784](https://boldapps.atlassian.net/browse/CHK-7784)
[CHK-7784]: https://boldapps.atlassian.net/browse/CHK-7784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7784: Fix Digital Wallets Not Working on Product Page for Logged-in Customers

---

Service/ExpressPay/QuoteConverter.php

- Account for product totals being recalculated when a cart level discount is present
When the following Magento settings are used:
Catalog Prices -> Including Tax
Apply Discount On Prices -> Including Tax
And a cart level discount is applied to a quote
Then Magento recalculates item subtotals to account for Cart Level Discounts
Here is an example:
Product price: $110
Tax rate: 10%
Cart level discount: 20%
Step 1 - Calculate base product price: 110/1.10 = 100
Step 2 - Apply discount INCLUDING tax: 110 * 0.2 = 22
Step 3 - Recalculate base price and tax: 
Price after discount = price - discount amount = 110 - 22 = 88
New base price = price after discount / tax rate = 88 / 1.10 = 80
New tax amount = 88 - 80 = 8
https://stage.lumicom.it/ has some custom behaviour updating quotes so that taxes …

CHK-6927: Fix Incorrect Item Total Sent To Checkout API When Prices Include Tax

---

Controller/Digitalwallets/Quote/Deactivate.php
Service/DigitalWallets/MagentoQuote/Deactivator.php
Test/Integration/Controller/Digitalwallets/Quote/DeactivateTest.php
Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
view/frontend/web/js/action/digital-wallets/deactivate-quote.js
view/frontend/web/js/model/spi.js

Resolves [CHK-7756](https://boldapps.atlassian.net/browse/CHK-7756)
[CHK-7756]: https://boldapps.atlassian.net/browse/CHK-7756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7756: Deactivate Digital Wallets Quote on Error or Cancellation

---

PATCHES.md
patches/CSP-PAYMENT-BOOSTER_2.3.x.patch
patches/CSP-PAYMENT-BOOSTER_COMPOSER_2.3.x.patch

Relates to [CHK-7629](https://boldapps.atlassian.net/browse/CHK-7629)
[CHK-7629]: https://boldapps.atlassian.net/browse/CHK-7629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7629: Add csp_whitelist.xml patch for composer version

---

view/frontend/web/js/action/express-pay/get-required-order-data-action.js

When the Digital Wallet buttons are initially loaded on the product pages, we need to send the product price to the `onRequireOrderData` callback to get the proper PayLater messaging (product price divided by 4). In any other scenarios, when the `onRequireOrderData` callback is called (on the product page or other places), we should still send the quote totals to make sure the Google Pay/Apple Pay modals are displaying taxes/shipping/fees properly.
Fixes [CHK-7948](https://boldapps.atlassian.net/browse/CHK-7948)
[CHK-7948]: https://boldapps.atlassian.net/browse/CHK-7948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHK-7948] Set correct totals for paylater messaging on product page

---

view/frontend/web/js/action/express-pay/get-required-order-data-action.js

Revert #215
This reverts commit 208be1e7b2e545fd22a506584ffd0081bfbbd788.
Resolves [CHK-7994](https://boldapps.atlassian.net/browse/CHK-7994)
[CHK-7994]: https://boldapps.atlassian.net/browse/CHK-7994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7994: Revert Pull Request 215

---

Plugin/Framework/App/FrontControllerPlugin.php
view/frontend/web/js/action/express-pay/get-required-order-data-action.js
view/frontend/web/js/express-pay-storefront.js

Reverts #209
This reverts commit 1212a18fbce56821a14003bf1b8c2428e3ef570f.
Resolves [CHK-7991](https://boldapps.atlassian.net/browse/CHK-7991)
[CHK-7991]: https://boldapps.atlassian.net/browse/CHK-7991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7991: Revert Pull Request 209

---

view/frontend/web/js/action/express-pay/get-required-order-data-action.js

Revert #226 
This reverts commit 1b09acb5be77b62c9c3c5c286827c944b182ca32, reversing changes made to c6d676b1e385b61ed22113dfdd03b4bba1aa783f.
Resolves [CHK-7996](https://boldapps.atlassian.net/browse/CHK-7996)
[CHK-7996]: https://boldapps.atlassian.net/browse/CHK-7996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7996: Revert Pull Request 226

---

Plugin/Framework/App/FrontControllerPlugin.php
view/frontend/web/js/action/express-pay/get-required-order-data-action.js
view/frontend/web/js/express-pay-storefront.js

Reverts #230  
Restores #209  
This reverts commit 61b67caf3965b284d7e7d673bdbcf4171d3412e1.
Resolves [CHK-7999](https://boldapps.atlassian.net/browse/CHK-7999)
[CHK-7999]: https://boldapps.atlassian.net/browse/CHK-7999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7999: Revert Pull Request 230

---

Plugin/Framework/App/ActionInterfacePlugin.php
Test/Integration/Plugin/Framework/App/ActionInterfacePluginTest.php
ViewModel/ExpressPay.php
etc/di.xml
etc/frontend/di.xml

Reverts #229  
Restores #212   
This reverts commit cc7d3234503780fde89b74998072e647edd7c817.
Resolves [CHK-8000](https://boldapps.atlassian.net/browse/CHK-8000)
[CHK-8000]: https://boldapps.atlassian.net/browse/CHK-8000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8000: Revert Pull Request 229

---

Controller/Digitalwallets/Quote/Deactivate.php
Service/DigitalWallets/MagentoQuote/Deactivator.php
Test/Integration/Controller/Digitalwallets/Quote/DeactivateTest.php
Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
view/frontend/web/js/action/digital-wallets/deactivate-quote.js
view/frontend/web/js/model/spi.js

Reverts #228   
Restores #218    
This reverts commit 444407d2c0ac12fbc40be62f675d232645d9e840.
Resolves [CHK-8001](https://boldapps.atlassian.net/browse/CHK-8001)
[CHK-8001]: https://boldapps.atlassian.net/browse/CHK-8001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8001: Revert Pull Request 228

---

view/frontend/web/js/action/express-pay/get-required-order-data-action.js

Reverts #231   
Restores #226    
This reverts commit 485dfe0c7431dff78ea80096880c3745e13f4c47.
Resolves [CHK-8003](https://boldapps.atlassian.net/browse/CHK-8003)
[CHK-8003]: https://boldapps.atlassian.net/browse/CHK-8003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8003: Revert Pull Request 231

---

composer.json

- CHK-7114: Support compatibility with Multi-currency extensions (#195)
- CHK-7315: Fix Express Pay multiple authorizations when ReCaptcha fails (#205)
- CHK-7256: Add Bold local env domain to style-src CSP whitelist (#214)
- CHK-7818: Fix namespace for DisableRecaptchaForExpressPayPlugin.php (#213)
- CHK-6927: Fix Incorrect Item Total Sent To Checkout API When Prices Include Tax (#202)
- CHK-7629: Update CSP Whitelist for 2.4.x Versions and Add Compatibility Patch for 2.3.x Versions (#196)
- CHK-7921: Resolve rounding issues (#219)
- CHK-7525: Show error and stop loader when tokenizing without iframe present (#207)
- CHK-7721: Add `public_order_id` to PayPal create order request (#223)
Resolves [CHK-7812](https://boldapps.atlassian.net/browse/CHK-7812)
[CHK-7812]: …

CHK-7812: Release Version 2.4.3

---

Controller/Digitalwallets/Checkout/GetConfig.php
view/frontend/web/js/express-pay-storefront.js

Resolves [CHK-8030](https://boldapps.atlassian.net/browse/CHK-8030)
[CHK-8030]: https://boldapps.atlassian.net/browse/CHK-8030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8030: Secure Get Bold Config AJAX Endpoint With Form Key

---

.github/workflows/pull-request-job.yml
.phpcs.xml
composer.json
phpstan.neon

Resolves [INFRA-2569](https://boldapps.atlassian.net/browse/INFRA-2569)
[INFRA-2569]: https://boldapps.atlassian.net/browse/INFRA-2569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INFRA-2569: Implement Workflow For Verifying Code Quality

---

view/frontend/web/js/mixin/payment-default-mixin.js

Fixes [CHK-8083](https://boldapps.atlassian.net/browse/CHK-8083)
[CHK-8083]: https://boldapps.atlassian.net/browse/CHK-8083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8083: Fix Inability To Place Order From Credit Card Form in Checkout

---

view/frontend/web/template/payment/spi.html

Fixes [CHK-8304](https://boldapps.atlassian.net/browse/CHK-8304)

CHK-8034: Disable Place Order Button on Payment Step of Checkout If No Billing Address Is Entered

---

Api/Data/Order/Payment/PaymentInterface.php
Api/ExpressPay/Order/CreateInterface.php
Api/ExpressPay/Order/GetInterface.php
Api/ExpressPay/Order/UpdateInterface.php
Service/ExpressPay/Order/Create.php
Service/ExpressPay/Order/Get.php
Service/ExpressPay/Order/Update.php
etc/di.xml
etc/webapi.xml

Fixes [CHK-8124](https://boldapps.atlassian.net/browse/CHK-8124)
[CHK-8124]: https://boldapps.atlassian.net/browse/CHK-8124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8124: Fix SOAP and Swagger API Errors

---

composer.json

- CHK-8034: Disable Place Order Button on Payment Step of Checkout If No Billing Address Is Entered _by_ @carolcastro1978 (#257)
- CHK-7753: Remove code adding VAT tax on the frontend for wallet pay options _by_ @DanielNordstrom (#254)
- CHK-8124: Fix SOAP and Swagger API Errors _by_ @JosephLeedy (#258)
Resolves [CHK-8134](https://boldapps.atlassian.net/browse/CHK-8134)
[CHK-8134]: https://boldapps.atlassian.net/browse/CHK-8134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8134: Release Version 2.5.1

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-8183](https://boldapps.atlassian.net/browse/CHK-8183)
[CHK-8183]: https://boldapps.atlassian.net/browse/CHK-8183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8183: Ensure EPS SDK is Rendered Only Once

---

.github/workflows/pull-request-integration-tests-job.yml
Cron/DigitalWallets/DeactivateQuotes.php
Model/Config/Backend/DigitalWallets/DeactivateQuotes.php
Model/Config/Source/Frequency.php
Service/DigitalWallets/MagentoQuote/Deactivator.php
Test/Integration/Cron/DigitalWallets/DeactivateQuotesTest.php
Test/Integration/Model/Config/Backend/DigitalWallets/DeactivateQuotesTest.php
Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
Test/Integration/_Stubs/Magento/Quote/Model/ResourceModel/Quote/CollectionStub.php
Test/Integration/_files/multiple_active_digital_wallets_quotes.php
Test/Integration/_files/multiple_active_digital_wallets_quotes_rollback.php
composer.json
etc/adminhtml/system.xml
etc/config.xml
etc/crontab.xml
etc/di.xml
etc/module.xml

Resolves [CHK-7757](https://boldapps.atlassian.net/browse/CHK-7757)
[CHK-7757]: https://boldapps.atlassian.net/browse/CHK-7757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7757: Automatically Clean Up Old Active Digital Wallets Quotes

---

Plugin/Checkout/Model/SessionPlugin.php
Test/Integration/Plugin/Checkout/Model/SessionPluginTest.php
Test/Integration/_files/digital_wallets_quote.php
Test/Integration/_files/digital_wallets_quote_rollback.php
etc/frontend/di.xml

Resolves [CHK-8082](https://boldapps.atlassian.net/browse/CHK-8082)
[CHK-8082]: https://boldapps.atlassian.net/browse/CHK-8082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8082: Prevent Clearing Quote From Session After Placing Digital Wallets Order

---

patches/Fix_bold_booster_magento_quote_bold_order_Schema-2.3.x.patch

Fixes [CHK-8187](https://boldapps.atlassian.net/browse/CHK-8187)
[CHK-8187]: https://boldapps.atlassian.net/browse/CHK-8187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8187: Fix Database Schema Error in Adobe Commerce 2.3

---

etc/adminhtml/system.xml

Relates to [CHK-7757](https://boldapps.atlassian.net/browse/CHK-7757)
[CHK-7757]: https://boldapps.atlassian.net/browse/CHK-7757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-7757: Add Missing Dependency to Retention Period Configuration Field

---

composer.json

- CHK-7757: Automatically Clean Up Old Active Digital Wallets Quotes _by_ @JosephLeedy (#260)
- CHK-8183: Ensure EPS SDK is Rendered Only Once _by_ @NickolasMalovanets (#261)
- CHK-8082: Prevent Clearing Quote From Session After Placing Digital Wallets Order _by_ @JosephLeedy (#262)
- CHK-8187: Fix Database Schema Error in Adobe Commerce 2.3 _by_ @JosephLeedy (#263)
- CHK-7757: Add Missing Dependency to Retention Period Configuration Field _by_ @JosephLeedy (#264)
- CHK-7757: Fix PHP Version Incompatibility With Cron Task _by_ @JosephLeedy (#265)
Resolves [CHK-8203](https://boldapps.atlassian.net/browse/CHK-8203)
[CHK-8203]: https://boldapps.atlassian.net/browse/CHK-8203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8203: Release Version 2.5.2

---

composer.json
etc/module.xml

Resolves [CHK-8176](https://boldapps.atlassian.net/browse/CHK-8176)
[CHK-8176]: https://boldapps.atlassian.net/browse/CHK-8176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8176: Declare Missing Dependencies

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-8217](https://boldapps.atlassian.net/browse/CHK-8217)
[CHK-8217]: https://boldapps.atlassian.net/browse/CHK-8217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page

---

view/frontend/web/js/view/payment/method-renderer/bold-spi.js

Fixes [CHK-8217](https://boldapps.atlassian.net/browse/CHK-8217)
[CHK-8217]: https://boldapps.atlassian.net/browse/CHK-8217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page

---

composer.json

- CHK-8176: Declare Missing Dependencies _by_ @JosephLeedy (#267)
- CHK-8176: Remove Unused Dependencies _by_ @JosephLeedy (#268)
- CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page _by_ @NickolasMalovanets (#269)
- CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page _by_ @NickolasMalovanets (#272)
Resolves [CHK-8260](https://boldapps.atlassian.net/browse/CHK-8260)
[CHK-8260]: https://boldapps.atlassian.net/browse/CHK-8260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8260: Release Version v2.5.3

---

composer.json

Resolves [CHK-8176](https://boldapps.atlassian.net/browse/CHK-8176)
[CHK-8176]: https://boldapps.atlassian.net/browse/CHK-8176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CHK-8176: Declare Missing Dependencies (Redux)

---

Api/ExpressPay/Order/CreateInterface.php
Model/CheckoutData.php
Service/ExpressPay/Order/Create.php
Test/Integration/Service/ExpressPay/Order/CreateTest.php
view/frontend/web/js/action/express-pay/create-wallet-pay-order-action.js

- Adds support for vaulting a card as a part of the PPCP order create workflow

CHK-8302: Vault new cards in PPCP

---

Test/Integration/Service/ExpressPay/Order/CreateTest.php

CHK-8803: Fix tests

---

composer.json

CHK-9142 CHK-9151 Version 2.6.3
